plugins { id "com.android.application" }

android {
    namespace "com.futbol.tv"
    compileSdk 35

    defaultConfig {
        applicationId "com.futbol.tv"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "0.1"
    }
}

dependencies {
    implementation "androidx.media3:media3-exoplayer:1.4.1"
    implementation "androidx.media3:media3-exoplayer-hls:1.4.1"
    implementation "androidx.media3:media3-ui:1.4.1"
}
